[package]
authors = ["trevyn <trevyn-git@protonmail.com>"]
description = "Turbocharger example."
edition = "2018"
name = "example"
publish = false
version = "0.1.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
turbocharger = {path = "../turbocharger", version = "=0.1.0"}
