[workspace]
members = [
  "example-full",
  "example-minimal",
  "example-turbosql",
  "turbocharger",
  "turbocharger-impl",
]

[patch.crates-io]
js-sys = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
wasm-bindgen = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
wasm-bindgen-futures = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
web-sys = {git = "https://github.com/Jules-Bertholet/wasm-bindgen", branch = "jsvalue-math"}
