name: ci

on:
  push:
  pull_request:
  schedule: [cron: '40 8 * * *']

env:
  CARGO_TERM_COLOR: always

jobs:
  checklinks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: trevyn/lychee-action@v1
        id: lychee
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: ./**/*.* --verbose --no-progress --exclude-all-private --base="http://127.0.0.1" --headers="accept=text/html" --scheme=http --scheme=https --scheme=mailto

      - name: Fail if there were link-check errors
        run: exit ${{ steps.lychee.outputs.exit_code }}

  build:
    name: build ${{ matrix.os }} rust ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-11.0]
        rust: [1.54, stable, beta, nightly-2021-09-16]
#              1.54 is minimum rustc version
        # nightly pinned due to https://github.com/rust-lang/cargo/issues/9919


    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
          components: clippy
          targets: wasm32-unknown-unknown

      - run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - run: git submodule update --remote

      - run: npm run build
        working-directory: 'turbocharger-template'
      - run: npm audit
        working-directory: 'turbocharger-template'
      - run: npm run test-ci
        working-directory: 'turbocharger-template'
