name: publish

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, 'turbocharger@0')"

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'true'

      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: stable
      
      - run: cargo doc --no-deps
        working-directory: 'turbocharger'

      - name: cargo publish turbocharger-impl
        run: cargo publish --no-verify --allow-dirty --token ${{ secrets.CARGO_TOKEN }}
        working-directory: 'turbocharger-impl'

      - name: cargo publish turbocharger
        run: cargo publish --no-verify --allow-dirty --token ${{ secrets.CARGO_TOKEN }}
        working-directory: 'turbocharger'
